parser: '@typescript-eslint/parser'

extends:
  - plugin:@typescript-eslint/recommended
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'
  - 'plugin:react/recommended'

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: ./tsconfig.json

rules:
  '@typescript-eslint/semi':
    - error
    - never
  '@typescript-eslint/no-explicit-any':
    - off
    - never
  '@typescript-eslint/naming-convention':
    - error
    - selector: interface
      format:
      - PascalCase
      custom:
        regex: "^I[A-Z]"
        match: false
  '@typescript-eslint/no-use-before-define':
    - off
    - never

settings:
  react:
    version: detect
